version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      lit:
        patterns:
          - "lit"
          - "lit-*"
      rollup:
        patterns:
          - "rollup"
          - "@rollup/*"
          - "rollup-plugin-*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "typescript-eslint"
      testing:
        patterns:
          - "@web/test-runner*"
          - "@open-wc/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
